// Generated by `npm run db:types` (supabase gen types typescript --local). Do not edit manually.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export type Database = {
  
  "graphql_public": {
          Tables: {
            [_ in never]: never
          }
          Views: {
            [_ in never]: never
          }
          Functions: {
            "graphql":
{ Args: { "extensions"?: Json,"operationName"?: string,"query"?: string,"variables"?: Json }; Returns: Json
                           }
          }
          Enums: {
            [_ in never]: never
          }
          CompositeTypes: {
            [_ in never]: never
          }
        },"public": {
          Tables: {
            "attachments": {
                  Row: {
                    "bucket": string,"created_at": string,"file_name": string,"id": string,"invoice_id": string | null,"message_id": string | null,"mime_type": string,"request_id": string | null,"size_bytes": number,"storage_path": string,"uploaded_by": string | null,"visibility": Database["public"]['Enums']["visibility_level"],"visit_id": string | null
                  }
                  ComputedFields: never
                  Insert: {
                    "bucket": string,"created_at"?: string,"file_name": string,"id"?: string,"invoice_id"?: string | null,"message_id"?: string | null,"mime_type": string,"request_id"?: string | null,"size_bytes": number,"storage_path": string,"uploaded_by"?: string | null,"visibility"?: Database["public"]['Enums']["visibility_level"],"visit_id"?: string | null
                  }
                  Update: {
                    "bucket"?: string,"created_at"?: string,"file_name"?: string,"id"?: string,"invoice_id"?: string | null,"message_id"?: string | null,"mime_type"?: string,"request_id"?: string | null,"size_bytes"?: number,"storage_path"?: string,"uploaded_by"?: string | null,"visibility"?: Database["public"]['Enums']["visibility_level"],"visit_id"?: string | null
                  }
                  Relationships: [
                    {
      foreignKeyName: "attachments_invoice_same_request"
      columns: ["invoice_id","request_id"]
isOneToOne: false
      referencedRelation: "invoices"
      referencedColumns: ["id","request_id"]
    },{
      foreignKeyName: "attachments_message_id_fkey"
      columns: ["message_id"]
isOneToOne: false
      referencedRelation: "messages"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "attachments_request_id_fkey"
      columns: ["request_id"]
isOneToOne: false
      referencedRelation: "dispatcher_queue"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "attachments_request_id_fkey"
      columns: ["request_id"]
isOneToOne: false
      referencedRelation: "requests"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "attachments_uploaded_by_fkey"
      columns: ["uploaded_by"]
isOneToOne: false
      referencedRelation: "profiles"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "attachments_visit_same_request"
      columns: ["visit_id","request_id"]
isOneToOne: false
      referencedRelation: "visits"
      referencedColumns: ["id","request_id"]
    }
                  ]
                },"automation_runs": {
                  Row: {
                    "confidence": number | null,"corrected_at": string | null,"corrected_by": string | null,"correction_reason": string | null,"created_at": string,"decision": Database["public"]['Enums']["automation_decision"] | null,"error_code": string | null,"error_text": string | null,"finished_at": string | null,"id": string,"input_version": number | null,"message_id": string | null,"operation_key": string,"request_id": string | null,"result": Json | null,"started_at": string,"status": Database["public"]['Enums']["automation_status"],"step": Database["public"]['Enums']["automation_step"],"updated_at": string,"workflow_execution_id": string | null
                  }
                  ComputedFields: never
                  Insert: {
                    "confidence"?: number | null,"corrected_at"?: string | null,"corrected_by"?: string | null,"correction_reason"?: string | null,"created_at"?: string,"decision"?: Database["public"]['Enums']["automation_decision"] | null,"error_code"?: string | null,"error_text"?: string | null,"finished_at"?: string | null,"id"?: string,"input_version"?: number | null,"message_id"?: string | null,"operation_key": string,"request_id"?: string | null,"result"?: Json | null,"started_at"?: string,"status"?: Database["public"]['Enums']["automation_status"],"step": Database["public"]['Enums']["automation_step"],"updated_at"?: string,"workflow_execution_id"?: string | null
                  }
                  Update: {
                    "confidence"?: number | null,"corrected_at"?: string | null,"corrected_by"?: string | null,"correction_reason"?: string | null,"created_at"?: string,"decision"?: Database["public"]['Enums']["automation_decision"] | null,"error_code"?: string | null,"error_text"?: string | null,"finished_at"?: string | null,"id"?: string,"input_version"?: number | null,"message_id"?: string | null,"operation_key"?: string,"request_id"?: string | null,"result"?: Json | null,"started_at"?: string,"status"?: Database["public"]['Enums']["automation_status"],"step"?: Database["public"]['Enums']["automation_step"],"updated_at"?: string,"workflow_execution_id"?: string | null
                  }
                  Relationships: [
                    {
      foreignKeyName: "automation_runs_corrected_by_fkey"
      columns: ["corrected_by"]
isOneToOne: false
      referencedRelation: "profiles"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "automation_runs_message_id_fkey"
      columns: ["message_id"]
isOneToOne: false
      referencedRelation: "messages"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "automation_runs_request_id_fkey"
      columns: ["request_id"]
isOneToOne: false
      referencedRelation: "dispatcher_queue"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "automation_runs_request_id_fkey"
      columns: ["request_id"]
isOneToOne: false
      referencedRelation: "requests"
      referencedColumns: ["id"]
    }
                  ]
                },"employee_availability": {
                  Row: {
                    "created_at": string,"employee_id": string,"ends_at": string | null,"id": string,"kind": Database["public"]['Enums']["availability_kind"],"label": string | null,"local_end": string | null,"local_start": string | null,"starts_at": string | null,"updated_at": string,"valid_from": string | null,"valid_to": string | null,"weekday": number | null
                  }
                  ComputedFields: never
                  Insert: {
                    "created_at"?: string,"employee_id": string,"ends_at"?: string | null,"id"?: string,"kind": Database["public"]['Enums']["availability_kind"],"label"?: string | null,"local_end"?: string | null,"local_start"?: string | null,"starts_at"?: string | null,"updated_at"?: string,"valid_from"?: string | null,"valid_to"?: string | null,"weekday"?: number | null
                  }
                  Update: {
                    "created_at"?: string,"employee_id"?: string,"ends_at"?: string | null,"id"?: string,"kind"?: Database["public"]['Enums']["availability_kind"],"label"?: string | null,"local_end"?: string | null,"local_start"?: string | null,"starts_at"?: string | null,"updated_at"?: string,"valid_from"?: string | null,"valid_to"?: string | null,"weekday"?: number | null
                  }
                  Relationships: [
                    {
      foreignKeyName: "employee_availability_employee_id_fkey"
      columns: ["employee_id"]
isOneToOne: false
      referencedRelation: "profiles"
      referencedColumns: ["id"]
    }
                  ]
                },"invoice_items": {
                  Row: {
                    "created_at": string,"description": string,"gross_amount": number,"id": string,"invoice_id": string,"kind": Database["public"]['Enums']["work_entry_kind"],"net_amount": number,"position": number,"quantity": number,"tax_amount": number,"tax_rate": number,"unit": Database["public"]['Enums']["work_unit"],"unit_price": number,"work_entry_id": string | null
                  }
                  ComputedFields: never
                  Insert: {
                    "created_at"?: string,"description": string,"gross_amount": number,"id"?: string,"invoice_id": string,"kind": Database["public"]['Enums']["work_entry_kind"],"net_amount": number,"position": number,"quantity": number,"tax_amount": number,"tax_rate": number,"unit": Database["public"]['Enums']["work_unit"],"unit_price": number,"work_entry_id"?: string | null
                  }
                  Update: {
                    "created_at"?: string,"description"?: string,"gross_amount"?: number,"id"?: string,"invoice_id"?: string,"kind"?: Database["public"]['Enums']["work_entry_kind"],"net_amount"?: number,"position"?: number,"quantity"?: number,"tax_amount"?: number,"tax_rate"?: number,"unit"?: Database["public"]['Enums']["work_unit"],"unit_price"?: number,"work_entry_id"?: string | null
                  }
                  Relationships: [
                    {
      foreignKeyName: "invoice_items_invoice_id_fkey"
      columns: ["invoice_id"]
isOneToOne: false
      referencedRelation: "invoices"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "invoice_items_work_entry_id_fkey"
      columns: ["work_entry_id"]
isOneToOne: true
      referencedRelation: "work_entries"
      referencedColumns: ["id"]
    }
                  ]
                },"invoice_number_counters": {
                  Row: {
                    "last_value": number,"year": number
                  }
                  ComputedFields: never
                  Insert: {
                    "last_value": number,"year": number
                  }
                  Update: {
                    "last_value"?: number,"year"?: number
                  }
                  Relationships: [
                    
                  ]
                },"invoices": {
                  Row: {
                    "created_at": string,"created_by": string,"currency": string,"customer_snapshot": NonNullable<Json>,"id": string,"invoice_number": string | null,"issue_date": string | null,"issued_at": string | null,"issued_by": string | null,"notes": string | null,"paid_at": string | null,"payment_due_date": string | null,"request_id": string,"seller_snapshot": NonNullable<Json>,"sent_at": string | null,"status": Database["public"]['Enums']["invoice_status"],"subtotal": number,"tax_total": number,"total": number,"updated_at": string
                  }
                  ComputedFields: never
                  Insert: {
                    "created_at"?: string,"created_by": string,"currency"?: string,"customer_snapshot"?: NonNullable<Json>,"id"?: string,"invoice_number"?: string | null,"issue_date"?: string | null,"issued_at"?: string | null,"issued_by"?: string | null,"notes"?: string | null,"paid_at"?: string | null,"payment_due_date"?: string | null,"request_id": string,"seller_snapshot"?: NonNullable<Json>,"sent_at"?: string | null,"status"?: Database["public"]['Enums']["invoice_status"],"subtotal"?: number,"tax_total"?: number,"total"?: number,"updated_at"?: string
                  }
                  Update: {
                    "created_at"?: string,"created_by"?: string,"currency"?: string,"customer_snapshot"?: NonNullable<Json>,"id"?: string,"invoice_number"?: string | null,"issue_date"?: string | null,"issued_at"?: string | null,"issued_by"?: string | null,"notes"?: string | null,"paid_at"?: string | null,"payment_due_date"?: string | null,"request_id"?: string,"seller_snapshot"?: NonNullable<Json>,"sent_at"?: string | null,"status"?: Database["public"]['Enums']["invoice_status"],"subtotal"?: number,"tax_total"?: number,"total"?: number,"updated_at"?: string
                  }
                  Relationships: [
                    {
      foreignKeyName: "invoices_created_by_fkey"
      columns: ["created_by"]
isOneToOne: false
      referencedRelation: "profiles"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "invoices_issued_by_fkey"
      columns: ["issued_by"]
isOneToOne: false
      referencedRelation: "profiles"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "invoices_request_id_fkey"
      columns: ["request_id"]
isOneToOne: true
      referencedRelation: "dispatcher_queue"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "invoices_request_id_fkey"
      columns: ["request_id"]
isOneToOne: true
      referencedRelation: "requests"
      referencedColumns: ["id"]
    }
                  ]
                },"messages": {
                  Row: {
                    "approved_at": string | null,"approved_by": string | null,"author_id": string | null,"body_text": string,"created_at": string,"direction": Database["public"]['Enums']["message_direction"],"error_text": string | null,"from_address": string | null,"gmail_message_id": string | null,"gmail_thread_id": string | null,"handled_at": string | null,"id": string,"in_reply_to": string | null,"inbox_dispatcher_id": string | null,"invoice_id": string | null,"kind": Database["public"]['Enums']["message_kind"],"mailbox_key": string | null,"mime_message_id": string | null,"received_at": string | null,"references_header": (string)[] | null,"request_id": string | null,"sent_at": string | null,"status": Database["public"]['Enums']["message_status"],"subject": string,"to_address": string | null,"updated_at": string
                  }
                  ComputedFields: never
                  Insert: {
                    "approved_at"?: string | null,"approved_by"?: string | null,"author_id"?: string | null,"body_text": string,"created_at"?: string,"direction": Database["public"]['Enums']["message_direction"],"error_text"?: string | null,"from_address"?: string | null,"gmail_message_id"?: string | null,"gmail_thread_id"?: string | null,"handled_at"?: string | null,"id"?: string,"in_reply_to"?: string | null,"inbox_dispatcher_id"?: string | null,"invoice_id"?: string | null,"kind": Database["public"]['Enums']["message_kind"],"mailbox_key"?: string | null,"mime_message_id"?: string | null,"received_at"?: string | null,"references_header"?: (string)[] | null,"request_id"?: string | null,"sent_at"?: string | null,"status": Database["public"]['Enums']["message_status"],"subject": string,"to_address"?: string | null,"updated_at"?: string
                  }
                  Update: {
                    "approved_at"?: string | null,"approved_by"?: string | null,"author_id"?: string | null,"body_text"?: string,"created_at"?: string,"direction"?: Database["public"]['Enums']["message_direction"],"error_text"?: string | null,"from_address"?: string | null,"gmail_message_id"?: string | null,"gmail_thread_id"?: string | null,"handled_at"?: string | null,"id"?: string,"in_reply_to"?: string | null,"inbox_dispatcher_id"?: string | null,"invoice_id"?: string | null,"kind"?: Database["public"]['Enums']["message_kind"],"mailbox_key"?: string | null,"mime_message_id"?: string | null,"received_at"?: string | null,"references_header"?: (string)[] | null,"request_id"?: string | null,"sent_at"?: string | null,"status"?: Database["public"]['Enums']["message_status"],"subject"?: string,"to_address"?: string | null,"updated_at"?: string
                  }
                  Relationships: [
                    {
      foreignKeyName: "messages_approved_by_fkey"
      columns: ["approved_by"]
isOneToOne: false
      referencedRelation: "profiles"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "messages_author_id_fkey"
      columns: ["author_id"]
isOneToOne: false
      referencedRelation: "profiles"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "messages_inbox_dispatcher_id_fkey"
      columns: ["inbox_dispatcher_id"]
isOneToOne: false
      referencedRelation: "profiles"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "messages_invoice_same_request"
      columns: ["invoice_id","request_id"]
isOneToOne: false
      referencedRelation: "invoices"
      referencedColumns: ["id","request_id"]
    },{
      foreignKeyName: "messages_request_id_fkey"
      columns: ["request_id"]
isOneToOne: false
      referencedRelation: "dispatcher_queue"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "messages_request_id_fkey"
      columns: ["request_id"]
isOneToOne: false
      referencedRelation: "requests"
      referencedColumns: ["id"]
    }
                  ]
                },"profiles": {
                  Row: {
                    "created_at": string,"display_name": string,"id": string,"is_active": boolean,"role": Database["public"]['Enums']["employee_role"],"updated_at": string
                  }
                  ComputedFields: never
                  Insert: {
                    "created_at"?: string,"display_name": string,"id": string,"is_active"?: boolean,"role": Database["public"]['Enums']["employee_role"],"updated_at"?: string
                  }
                  Update: {
                    "created_at"?: string,"display_name"?: string,"id"?: string,"is_active"?: boolean,"role"?: Database["public"]['Enums']["employee_role"],"updated_at"?: string
                  }
                  Relationships: [
                    
                  ]
                },"request_events": {
                  Row: {
                    "actor_id": string | null,"actor_type": Database["public"]['Enums']["actor_type"],"created_at": string,"data": NonNullable<Json>,"event_type": string,"from_value": string | null,"id": string,"note": string | null,"occurred_at": string,"request_id": string,"seq": number,"to_value": string | null,"visibility": Database["public"]['Enums']["visibility_level"],"visit_id": string | null
                  }
                  ComputedFields: never
                  Insert: {
                    "actor_id"?: string | null,"actor_type": Database["public"]['Enums']["actor_type"],"created_at"?: string,"data"?: NonNullable<Json>,"event_type": string,"from_value"?: string | null,"id"?: string,"note"?: string | null,"occurred_at"?: string,"request_id": string,"seq"?: never,"to_value"?: string | null,"visibility"?: Database["public"]['Enums']["visibility_level"],"visit_id"?: string | null
                  }
                  Update: {
                    "actor_id"?: string | null,"actor_type"?: Database["public"]['Enums']["actor_type"],"created_at"?: string,"data"?: NonNullable<Json>,"event_type"?: string,"from_value"?: string | null,"id"?: string,"note"?: string | null,"occurred_at"?: string,"request_id"?: string,"seq"?: never,"to_value"?: string | null,"visibility"?: Database["public"]['Enums']["visibility_level"],"visit_id"?: string | null
                  }
                  Relationships: [
                    {
      foreignKeyName: "request_events_actor_id_fkey"
      columns: ["actor_id"]
isOneToOne: false
      referencedRelation: "profiles"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "request_events_request_id_fkey"
      columns: ["request_id"]
isOneToOne: false
      referencedRelation: "dispatcher_queue"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "request_events_request_id_fkey"
      columns: ["request_id"]
isOneToOne: false
      referencedRelation: "requests"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "request_events_visit_same_request"
      columns: ["visit_id","request_id"]
isOneToOne: false
      referencedRelation: "visits"
      referencedColumns: ["id","request_id"]
    }
                  ]
                },"request_number_counters": {
                  Row: {
                    "last_value": number,"year": number
                  }
                  ComputedFields: never
                  Insert: {
                    "last_value": number,"year": number
                  }
                  Update: {
                    "last_value"?: number,"year"?: number
                  }
                  Relationships: [
                    
                  ]
                },"requests": {
                  Row: {
                    "business_email": string,"cancellation_reason": string | null,"cancelled_at": string | null,"city": string,"company_name": string,"completed_at": string | null,"completion_summary": string | null,"contact_name": string,"created_at": string,"customer_number": string | null,"customer_urgency": Database["public"]['Enums']["customer_urgency"],"description": string,"dispatcher_id": string | null,"emergency_sla_claimed": boolean | null,"equipment_kind": Database["public"]['Enums']["equipment_kind"],"first_substantive_response_at": string | null,"human_review_required": boolean,"id": string,"intake_completed_at": string | null,"intake_mode": Database["public"]['Enums']["intake_mode"] | null,"intake_status": Database["public"]['Enums']["intake_status"],"is_demo": boolean,"machine_number": string | null,"manual_minutes_baseline": number | null,"manufacturer": string | null,"model_type": string | null,"phone_number": string,"postal_code": string,"priority": Database["public"]['Enums']["request_priority"] | null,"raw_payload": NonNullable<Json>,"rejection_reason": string | null,"request_number": string,"requested_visit_date": string,"response_due_at": string | null,"safety_risk": Database["public"]['Enums']["safety_risk"],"service_due_at": string | null,"service_kind": Database["public"]['Enums']["service_kind"],"site_label": string | null,"sla_contract_number": string | null,"sla_verified": boolean,"source": string,"source_event_key": string,"street_house_number": string,"technician_id": string | null,"updated_at": string,"version": number,"work_status": Database["public"]['Enums']["work_status"]
                  }
                  ComputedFields: never
                  Insert: {
                    "business_email": string,"cancellation_reason"?: string | null,"cancelled_at"?: string | null,"city": string,"company_name": string,"completed_at"?: string | null,"completion_summary"?: string | null,"contact_name": string,"created_at"?: string,"customer_number"?: string | null,"customer_urgency": Database["public"]['Enums']["customer_urgency"],"description": string,"dispatcher_id"?: string | null,"emergency_sla_claimed"?: boolean | null,"equipment_kind": Database["public"]['Enums']["equipment_kind"],"first_substantive_response_at"?: string | null,"human_review_required"?: boolean,"id"?: string,"intake_completed_at"?: string | null,"intake_mode"?: Database["public"]['Enums']["intake_mode"] | null,"intake_status"?: Database["public"]['Enums']["intake_status"],"is_demo"?: boolean,"machine_number"?: string | null,"manual_minutes_baseline"?: number | null,"manufacturer"?: string | null,"model_type"?: string | null,"phone_number": string,"postal_code": string,"priority"?: Database["public"]['Enums']["request_priority"] | null,"raw_payload": NonNullable<Json>,"rejection_reason"?: string | null,"request_number": string,"requested_visit_date": string,"response_due_at"?: string | null,"safety_risk": Database["public"]['Enums']["safety_risk"],"service_due_at"?: string | null,"service_kind": Database["public"]['Enums']["service_kind"],"site_label"?: string | null,"sla_contract_number"?: string | null,"sla_verified"?: boolean,"source": string,"source_event_key": string,"street_house_number": string,"technician_id"?: string | null,"updated_at"?: string,"version"?: number,"work_status"?: Database["public"]['Enums']["work_status"]
                  }
                  Update: {
                    "business_email"?: string,"cancellation_reason"?: string | null,"cancelled_at"?: string | null,"city"?: string,"company_name"?: string,"completed_at"?: string | null,"completion_summary"?: string | null,"contact_name"?: string,"created_at"?: string,"customer_number"?: string | null,"customer_urgency"?: Database["public"]['Enums']["customer_urgency"],"description"?: string,"dispatcher_id"?: string | null,"emergency_sla_claimed"?: boolean | null,"equipment_kind"?: Database["public"]['Enums']["equipment_kind"],"first_substantive_response_at"?: string | null,"human_review_required"?: boolean,"id"?: string,"intake_completed_at"?: string | null,"intake_mode"?: Database["public"]['Enums']["intake_mode"] | null,"intake_status"?: Database["public"]['Enums']["intake_status"],"is_demo"?: boolean,"machine_number"?: string | null,"manual_minutes_baseline"?: number | null,"manufacturer"?: string | null,"model_type"?: string | null,"phone_number"?: string,"postal_code"?: string,"priority"?: Database["public"]['Enums']["request_priority"] | null,"raw_payload"?: NonNullable<Json>,"rejection_reason"?: string | null,"request_number"?: string,"requested_visit_date"?: string,"response_due_at"?: string | null,"safety_risk"?: Database["public"]['Enums']["safety_risk"],"service_due_at"?: string | null,"service_kind"?: Database["public"]['Enums']["service_kind"],"site_label"?: string | null,"sla_contract_number"?: string | null,"sla_verified"?: boolean,"source"?: string,"source_event_key"?: string,"street_house_number"?: string,"technician_id"?: string | null,"updated_at"?: string,"version"?: number,"work_status"?: Database["public"]['Enums']["work_status"]
                  }
                  Relationships: [
                    {
      foreignKeyName: "requests_dispatcher_id_fkey"
      columns: ["dispatcher_id"]
isOneToOne: false
      referencedRelation: "profiles"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "requests_technician_id_fkey"
      columns: ["technician_id"]
isOneToOne: false
      referencedRelation: "profiles"
      referencedColumns: ["id"]
    }
                  ]
                },"service_rates": {
                  Row: {
                    "billing_model": Database["public"]['Enums']["billing_model"],"code": string,"created_at": string,"display_name": string,"id": string,"is_active": boolean,"service_kind": Database["public"]['Enums']["service_kind"],"tax_rate": number,"unit_price": number,"updated_at": string
                  }
                  ComputedFields: never
                  Insert: {
                    "billing_model": Database["public"]['Enums']["billing_model"],"code": string,"created_at"?: string,"display_name": string,"id"?: string,"is_active"?: boolean,"service_kind": Database["public"]['Enums']["service_kind"],"tax_rate": number,"unit_price": number,"updated_at"?: string
                  }
                  Update: {
                    "billing_model"?: Database["public"]['Enums']["billing_model"],"code"?: string,"created_at"?: string,"display_name"?: string,"id"?: string,"is_active"?: boolean,"service_kind"?: Database["public"]['Enums']["service_kind"],"tax_rate"?: number,"unit_price"?: number,"updated_at"?: string
                  }
                  Relationships: [
                    
                  ]
                },"settings": {
                  Row: {
                    "company_details": NonNullable<Json>,"created_at": string,"currency": string,"default_tax_rate": number,"id": number,"manual_intake_minutes": number,"payment_terms_days": number,"timezone": string,"updated_at": string,"updated_by": string | null
                  }
                  ComputedFields: never
                  Insert: {
                    "company_details"?: NonNullable<Json>,"created_at"?: string,"currency"?: string,"default_tax_rate"?: number,"id"?: number,"manual_intake_minutes"?: number,"payment_terms_days"?: number,"timezone"?: string,"updated_at"?: string,"updated_by"?: string | null
                  }
                  Update: {
                    "company_details"?: NonNullable<Json>,"created_at"?: string,"currency"?: string,"default_tax_rate"?: number,"id"?: number,"manual_intake_minutes"?: number,"payment_terms_days"?: number,"timezone"?: string,"updated_at"?: string,"updated_by"?: string | null
                  }
                  Relationships: [
                    {
      foreignKeyName: "settings_updated_by_fkey"
      columns: ["updated_by"]
isOneToOne: false
      referencedRelation: "profiles"
      referencedColumns: ["id"]
    }
                  ]
                },"visits": {
                  Row: {
                    "actual_end": string | null,"actual_start": string | null,"actual_work_minutes": number | null,"cancellation_reason": string | null,"created_at": string,"created_by": string,"id": string,"request_id": string,"scheduled_end": string,"scheduled_start": string,"status": Database["public"]['Enums']["visit_status"],"summary": string | null,"technician_id": string,"updated_at": string,"waiting_reason": string | null
                  }
                  ComputedFields: never
                  Insert: {
                    "actual_end"?: string | null,"actual_start"?: string | null,"actual_work_minutes"?: number | null,"cancellation_reason"?: string | null,"created_at"?: string,"created_by": string,"id"?: string,"request_id": string,"scheduled_end": string,"scheduled_start": string,"status"?: Database["public"]['Enums']["visit_status"],"summary"?: string | null,"technician_id": string,"updated_at"?: string,"waiting_reason"?: string | null
                  }
                  Update: {
                    "actual_end"?: string | null,"actual_start"?: string | null,"actual_work_minutes"?: number | null,"cancellation_reason"?: string | null,"created_at"?: string,"created_by"?: string,"id"?: string,"request_id"?: string,"scheduled_end"?: string,"scheduled_start"?: string,"status"?: Database["public"]['Enums']["visit_status"],"summary"?: string | null,"technician_id"?: string,"updated_at"?: string,"waiting_reason"?: string | null
                  }
                  Relationships: [
                    {
      foreignKeyName: "visits_created_by_fkey"
      columns: ["created_by"]
isOneToOne: false
      referencedRelation: "profiles"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "visits_request_id_fkey"
      columns: ["request_id"]
isOneToOne: false
      referencedRelation: "dispatcher_queue"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "visits_request_id_fkey"
      columns: ["request_id"]
isOneToOne: false
      referencedRelation: "requests"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "visits_technician_id_fkey"
      columns: ["technician_id"]
isOneToOne: false
      referencedRelation: "profiles"
      referencedColumns: ["id"]
    }
                  ]
                },"work_entries": {
                  Row: {
                    "author_id": string,"billable": boolean,"created_at": string,"description": string,"id": string,"item_status": Database["public"]['Enums']["work_item_status"],"kind": Database["public"]['Enums']["work_entry_kind"],"ordered_at": string | null,"performed_at": string | null,"quantity": number,"request_id": string,"service_rate_id": string | null,"tax_rate": number,"unit": Database["public"]['Enums']["work_unit"],"unit_price": number,"updated_at": string,"visit_id": string | null
                  }
                  ComputedFields: never
                  Insert: {
                    "author_id": string,"billable"?: boolean,"created_at"?: string,"description": string,"id"?: string,"item_status"?: Database["public"]['Enums']["work_item_status"],"kind": Database["public"]['Enums']["work_entry_kind"],"ordered_at"?: string | null,"performed_at"?: string | null,"quantity": number,"request_id": string,"service_rate_id"?: string | null,"tax_rate": number,"unit": Database["public"]['Enums']["work_unit"],"unit_price": number,"updated_at"?: string,"visit_id"?: string | null
                  }
                  Update: {
                    "author_id"?: string,"billable"?: boolean,"created_at"?: string,"description"?: string,"id"?: string,"item_status"?: Database["public"]['Enums']["work_item_status"],"kind"?: Database["public"]['Enums']["work_entry_kind"],"ordered_at"?: string | null,"performed_at"?: string | null,"quantity"?: number,"request_id"?: string,"service_rate_id"?: string | null,"tax_rate"?: number,"unit"?: Database["public"]['Enums']["work_unit"],"unit_price"?: number,"updated_at"?: string,"visit_id"?: string | null
                  }
                  Relationships: [
                    {
      foreignKeyName: "work_entries_author_id_fkey"
      columns: ["author_id"]
isOneToOne: false
      referencedRelation: "profiles"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "work_entries_request_id_fkey"
      columns: ["request_id"]
isOneToOne: false
      referencedRelation: "dispatcher_queue"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "work_entries_request_id_fkey"
      columns: ["request_id"]
isOneToOne: false
      referencedRelation: "requests"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "work_entries_service_rate_id_fkey"
      columns: ["service_rate_id"]
isOneToOne: false
      referencedRelation: "service_rates"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "work_entries_visit_same_request"
      columns: ["visit_id","request_id"]
isOneToOne: false
      referencedRelation: "visits"
      referencedColumns: ["id","request_id"]
    }
                  ]
                }
          }
          Views: {
            "dispatcher_queue": {
                  Row: {
                    "city": string | null,"company_name": string | null,"created_at": string | null,"customer_urgency": Database["public"]['Enums']["customer_urgency"] | null,"dispatcher_id": string | null,"due_at": string | null,"equipment_kind": Database["public"]['Enums']["equipment_kind"] | null,"human_review_required": boolean | null,"id": string | null,"intake_mode": Database["public"]['Enums']["intake_mode"] | null,"intake_status": Database["public"]['Enums']["intake_status"] | null,"is_demo": boolean | null,"priority": Database["public"]['Enums']["request_priority"] | null,"priority_rank": number | null,"queue": string | null,"request_number": string | null,"safety_check_required": boolean | null,"safety_risk": Database["public"]['Enums']["safety_risk"] | null,"service_kind": Database["public"]['Enums']["service_kind"] | null,"technician_id": string | null,"version": number | null,"waiting_since": string | null,"work_status": Database["public"]['Enums']["work_status"] | null
                  }
                  ComputedFields: never
                  Relationships: [
                    {
      foreignKeyName: "requests_dispatcher_id_fkey"
      columns: ["dispatcher_id"]
isOneToOne: false
      referencedRelation: "profiles"
      referencedColumns: ["id"]
    },{
      foreignKeyName: "requests_technician_id_fkey"
      columns: ["technician_id"]
isOneToOne: false
      referencedRelation: "profiles"
      referencedColumns: ["id"]
    }
                  ]
                }
          }
          Functions: {
            "add_visit_photo":
{ Args: { "expected_version": number,"file_name": string,"mime_type": string,"size_bytes": number,"storage_path": string,"visit_id": string }; Returns: {
              "bucket": string,
"created_at": string,
"file_name": string,
"id": string,
"invoice_id": string | null,
"message_id": string | null,
"mime_type": string,
"request_id": string | null,
"size_bytes": number,
"storage_path": string,
"uploaded_by": string | null,
"visibility": Database["public"]['Enums']["visibility_level"],
"visit_id": string | null
            }
                          SetofOptions: {
        from: "*"
        to: "attachments"
        isOneToOne: true
        isSetofReturn: false
      } },
"add_work_entry":
{ Args: { "billable"?: boolean,"description": string,"expected_version": number,"item_status"?: Database["public"]['Enums']["work_item_status"],"kind": Database["public"]['Enums']["work_entry_kind"],"quantity": number,"request_id": string,"service_rate_id"?: string,"tax_rate"?: number,"unit_price"?: number,"visit_id"?: string }; Returns: {
              "author_id": string,
"billable": boolean,
"created_at": string,
"description": string,
"id": string,
"item_status": Database["public"]['Enums']["work_item_status"],
"kind": Database["public"]['Enums']["work_entry_kind"],
"ordered_at": string | null,
"performed_at": string | null,
"quantity": number,
"request_id": string,
"service_rate_id": string | null,
"tax_rate": number,
"unit": Database["public"]['Enums']["work_unit"],
"unit_price": number,
"updated_at": string,
"visit_id": string | null
            }
                          SetofOptions: {
        from: "*"
        to: "work_entries"
        isOneToOne: true
        isSetofReturn: false
      } },
"admin_add_absence":
{ Args: { "employee_id": string,"ends_at": string,"label"?: string,"starts_at": string }; Returns: {
              "created_at": string,
"employee_id": string,
"ends_at": string | null,
"id": string,
"kind": Database["public"]['Enums']["availability_kind"],
"label": string | null,
"local_end": string | null,
"local_start": string | null,
"starts_at": string | null,
"updated_at": string,
"valid_from": string | null,
"valid_to": string | null,
"weekday": number | null
            }
                          SetofOptions: {
        from: "*"
        to: "employee_availability"
        isOneToOne: true
        isSetofReturn: false
      } },
"admin_deactivate_employee":
{ Args: { "employee_id": string,"replacement_id"?: string }; Returns: Json
                           },
"admin_delete_absence":
{ Args: { "absence_id": string }; Returns: undefined
                           },
"admin_employee_assignments":
{ Args: { "employee_id": string }; Returns: {
              "assignment": string,"company_name": string,"request_id": string,"request_number": string,"scheduled_end": string,"scheduled_start": string,"visit_id": string,"visit_status": Database["public"]['Enums']["visit_status"]
            }[]
                           },
"admin_reactivate_employee":
{ Args: { "employee_id": string }; Returns: {
              "created_at": string,
"display_name": string,
"id": string,
"is_active": boolean,
"role": Database["public"]['Enums']["employee_role"],
"updated_at": string
            }
                          SetofOptions: {
        from: "*"
        to: "profiles"
        isOneToOne: true
        isSetofReturn: false
      } },
"admin_save_service_rate":
{ Args: { "billing_model": Database["public"]['Enums']["billing_model"],"code": string,"display_name": string,"is_active": boolean,"rate_id": string,"service_kind": Database["public"]['Enums']["service_kind"],"tax_rate": number,"unit_price": number }; Returns: {
              "billing_model": Database["public"]['Enums']["billing_model"],
"code": string,
"created_at": string,
"display_name": string,
"id": string,
"is_active": boolean,
"service_kind": Database["public"]['Enums']["service_kind"],
"tax_rate": number,
"unit_price": number,
"updated_at": string
            }
                          SetofOptions: {
        from: "*"
        to: "service_rates"
        isOneToOne: true
        isSetofReturn: false
      } },
"admin_set_working_hours":
{ Args: { "employee_id": string,"hours": Json }; Returns: {
              "created_at": string,
"employee_id": string,
"ends_at": string | null,
"id": string,
"kind": Database["public"]['Enums']["availability_kind"],
"label": string | null,
"local_end": string | null,
"local_start": string | null,
"starts_at": string | null,
"updated_at": string,
"valid_from": string | null,
"valid_to": string | null,
"weekday": number | null
            }[]
                          SetofOptions: {
        from: "*"
        to: "employee_availability"
        isOneToOne: false
        isSetofReturn: true
      } },
"admin_update_employee":
{ Args: { "display_name": string,"employee_id": string,"role": Database["public"]['Enums']["employee_role"] }; Returns: {
              "created_at": string,
"display_name": string,
"id": string,
"is_active": boolean,
"role": Database["public"]['Enums']["employee_role"],
"updated_at": string
            }
                          SetofOptions: {
        from: "*"
        to: "profiles"
        isOneToOne: true
        isSetofReturn: false
      } },
"admin_update_settings":
{ Args: { "company_details": Json,"default_tax_rate": number,"manual_intake_minutes": number,"payment_terms_days": number }; Returns: {
              "company_details": NonNullable<Json>,
"created_at": string,
"currency": string,
"default_tax_rate": number,
"id": number,
"manual_intake_minutes": number,
"payment_terms_days": number,
"timezone": string,
"updated_at": string,
"updated_by": string | null
            }
                          SetofOptions: {
        from: "*"
        to: "settings"
        isOneToOne: true
        isSetofReturn: false
      } },
"analytics_automation":
{ Args: { "anchor"?: string,"as_of"?: string,"kind"?: string }; Returns: {
              "corrected": number,"decision": Database["public"]['Enums']["automation_decision"],"runs": number,"status": Database["public"]['Enums']["automation_status"],"step": Database["public"]['Enums']["automation_step"]
            }[]
                           },
"analytics_kpis":
{ Args: { "anchor"?: string,"as_of"?: string,"kind"?: string }; Returns: {
              "change_percent": number,"current_value": number,"detail": Json,"difference": number,"key": string,"label": string,"measure": string,"previous_value": number,"unit": string
            }[]
                           },
"analytics_queue_history":
{ Args: { "from_date": string,"to_date": string }; Returns: {
              "day": string,"queue": string,"requests": number
            }[]
                           },
"analytics_series":
{ Args: { "from_date": string,"granularity": string,"to_date": string }; Returns: {
              "automatic_completed": number,"baseline_minutes": number,"bucket_start": string,"completed": number,"intake_completed": number,"invoiced_gross": number,"payments_received": number,"received": number,"saved_minutes": number,"saved_requests": number
            }[]
                           },
"analytics_team":
{ Args: { "anchor"?: string,"as_of"?: string,"kind"?: string }; Returns: {
              "display_name": string,"employee_id": string,"intake_completed": number,"is_active": boolean,"open_requests": number,"requests_completed": number,"role": Database["public"]['Enums']["employee_role"],"visits_completed": number,"work_minutes": number
            }[]
                           },
"analytics_window":
{ Args: { "anchor"?: string,"as_of"?: string,"kind"?: string }; Returns: {
              "current_end": string,"current_start": string,"is_complete": boolean,"period_end": string,"period_kind": string,"previous_end": string,"previous_start": string,"time_zone": string
            }[]
                           },
"apply_analysis_result":
{ Args: { "expected_version": number,"request_id": string,"result": Json,"run_id": string }; Returns: {
              "business_email": string,
"cancellation_reason": string | null,
"cancelled_at": string | null,
"city": string,
"company_name": string,
"completed_at": string | null,
"completion_summary": string | null,
"contact_name": string,
"created_at": string,
"customer_number": string | null,
"customer_urgency": Database["public"]['Enums']["customer_urgency"],
"description": string,
"dispatcher_id": string | null,
"emergency_sla_claimed": boolean | null,
"equipment_kind": Database["public"]['Enums']["equipment_kind"],
"first_substantive_response_at": string | null,
"human_review_required": boolean,
"id": string,
"intake_completed_at": string | null,
"intake_mode": Database["public"]['Enums']["intake_mode"] | null,
"intake_status": Database["public"]['Enums']["intake_status"],
"is_demo": boolean,
"machine_number": string | null,
"manual_minutes_baseline": number | null,
"manufacturer": string | null,
"model_type": string | null,
"phone_number": string,
"postal_code": string,
"priority": Database["public"]['Enums']["request_priority"] | null,
"raw_payload": NonNullable<Json>,
"rejection_reason": string | null,
"request_number": string,
"requested_visit_date": string,
"response_due_at": string | null,
"safety_risk": Database["public"]['Enums']["safety_risk"],
"service_due_at": string | null,
"service_kind": Database["public"]['Enums']["service_kind"],
"site_label": string | null,
"sla_contract_number": string | null,
"sla_verified": boolean,
"source": string,
"source_event_key": string,
"street_house_number": string,
"technician_id": string | null,
"updated_at": string,
"version": number,
"work_status": Database["public"]['Enums']["work_status"]
            }
                          SetofOptions: {
        from: "*"
        to: "requests"
        isOneToOne: true
        isSetofReturn: false
      } },
"assign_dispatcher":
{ Args: { "dispatcher_id": string,"expected_version": number,"request_id": string }; Returns: {
              "business_email": string,
"cancellation_reason": string | null,
"cancelled_at": string | null,
"city": string,
"company_name": string,
"completed_at": string | null,
"completion_summary": string | null,
"contact_name": string,
"created_at": string,
"customer_number": string | null,
"customer_urgency": Database["public"]['Enums']["customer_urgency"],
"description": string,
"dispatcher_id": string | null,
"emergency_sla_claimed": boolean | null,
"equipment_kind": Database["public"]['Enums']["equipment_kind"],
"first_substantive_response_at": string | null,
"human_review_required": boolean,
"id": string,
"intake_completed_at": string | null,
"intake_mode": Database["public"]['Enums']["intake_mode"] | null,
"intake_status": Database["public"]['Enums']["intake_status"],
"is_demo": boolean,
"machine_number": string | null,
"manual_minutes_baseline": number | null,
"manufacturer": string | null,
"model_type": string | null,
"phone_number": string,
"postal_code": string,
"priority": Database["public"]['Enums']["request_priority"] | null,
"raw_payload": NonNullable<Json>,
"rejection_reason": string | null,
"request_number": string,
"requested_visit_date": string,
"response_due_at": string | null,
"safety_risk": Database["public"]['Enums']["safety_risk"],
"service_due_at": string | null,
"service_kind": Database["public"]['Enums']["service_kind"],
"site_label": string | null,
"sla_contract_number": string | null,
"sla_verified": boolean,
"source": string,
"source_event_key": string,
"street_house_number": string,
"technician_id": string | null,
"updated_at": string,
"version": number,
"work_status": Database["public"]['Enums']["work_status"]
            }
                          SetofOptions: {
        from: "*"
        to: "requests"
        isOneToOne: true
        isSetofReturn: false
      } },
"cancel_request":
{ Args: { "expected_version": number,"reason": string,"request_id": string }; Returns: {
              "business_email": string,
"cancellation_reason": string | null,
"cancelled_at": string | null,
"city": string,
"company_name": string,
"completed_at": string | null,
"completion_summary": string | null,
"contact_name": string,
"created_at": string,
"customer_number": string | null,
"customer_urgency": Database["public"]['Enums']["customer_urgency"],
"description": string,
"dispatcher_id": string | null,
"emergency_sla_claimed": boolean | null,
"equipment_kind": Database["public"]['Enums']["equipment_kind"],
"first_substantive_response_at": string | null,
"human_review_required": boolean,
"id": string,
"intake_completed_at": string | null,
"intake_mode": Database["public"]['Enums']["intake_mode"] | null,
"intake_status": Database["public"]['Enums']["intake_status"],
"is_demo": boolean,
"machine_number": string | null,
"manual_minutes_baseline": number | null,
"manufacturer": string | null,
"model_type": string | null,
"phone_number": string,
"postal_code": string,
"priority": Database["public"]['Enums']["request_priority"] | null,
"raw_payload": NonNullable<Json>,
"rejection_reason": string | null,
"request_number": string,
"requested_visit_date": string,
"response_due_at": string | null,
"safety_risk": Database["public"]['Enums']["safety_risk"],
"service_due_at": string | null,
"service_kind": Database["public"]['Enums']["service_kind"],
"site_label": string | null,
"sla_contract_number": string | null,
"sla_verified": boolean,
"source": string,
"source_event_key": string,
"street_house_number": string,
"technician_id": string | null,
"updated_at": string,
"version": number,
"work_status": Database["public"]['Enums']["work_status"]
            }
                          SetofOptions: {
        from: "*"
        to: "requests"
        isOneToOne: true
        isSetofReturn: false
      } },
"cancel_visit":
{ Args: { "expected_version": number,"reason": string,"visit_id": string }; Returns: {
              "actual_end": string | null,
"actual_start": string | null,
"actual_work_minutes": number | null,
"cancellation_reason": string | null,
"created_at": string,
"created_by": string,
"id": string,
"request_id": string,
"scheduled_end": string,
"scheduled_start": string,
"status": Database["public"]['Enums']["visit_status"],
"summary": string | null,
"technician_id": string,
"updated_at": string,
"waiting_reason": string | null
            }
                          SetofOptions: {
        from: "*"
        to: "visits"
        isOneToOne: true
        isSetofReturn: false
      } },
"change_deadline":
{ Args: { "deadline_kind": string,"expected_version": number,"new_due_at": string,"reason": string,"request_id": string }; Returns: {
              "business_email": string,
"cancellation_reason": string | null,
"cancelled_at": string | null,
"city": string,
"company_name": string,
"completed_at": string | null,
"completion_summary": string | null,
"contact_name": string,
"created_at": string,
"customer_number": string | null,
"customer_urgency": Database["public"]['Enums']["customer_urgency"],
"description": string,
"dispatcher_id": string | null,
"emergency_sla_claimed": boolean | null,
"equipment_kind": Database["public"]['Enums']["equipment_kind"],
"first_substantive_response_at": string | null,
"human_review_required": boolean,
"id": string,
"intake_completed_at": string | null,
"intake_mode": Database["public"]['Enums']["intake_mode"] | null,
"intake_status": Database["public"]['Enums']["intake_status"],
"is_demo": boolean,
"machine_number": string | null,
"manual_minutes_baseline": number | null,
"manufacturer": string | null,
"model_type": string | null,
"phone_number": string,
"postal_code": string,
"priority": Database["public"]['Enums']["request_priority"] | null,
"raw_payload": NonNullable<Json>,
"rejection_reason": string | null,
"request_number": string,
"requested_visit_date": string,
"response_due_at": string | null,
"safety_risk": Database["public"]['Enums']["safety_risk"],
"service_due_at": string | null,
"service_kind": Database["public"]['Enums']["service_kind"],
"site_label": string | null,
"sla_contract_number": string | null,
"sla_verified": boolean,
"source": string,
"source_event_key": string,
"street_house_number": string,
"technician_id": string | null,
"updated_at": string,
"version": number,
"work_status": Database["public"]['Enums']["work_status"]
            }
                          SetofOptions: {
        from: "*"
        to: "requests"
        isOneToOne: true
        isSetofReturn: false
      } },
"claim_queued_messages":
{ Args: { "batch_limit"?: number,"lease_seconds"?: number }; Returns: Json[]
                           },
"close_request":
{ Args: { "completion_summary": string,"expected_version": number,"request_id": string }; Returns: {
              "business_email": string,
"cancellation_reason": string | null,
"cancelled_at": string | null,
"city": string,
"company_name": string,
"completed_at": string | null,
"completion_summary": string | null,
"contact_name": string,
"created_at": string,
"customer_number": string | null,
"customer_urgency": Database["public"]['Enums']["customer_urgency"],
"description": string,
"dispatcher_id": string | null,
"emergency_sla_claimed": boolean | null,
"equipment_kind": Database["public"]['Enums']["equipment_kind"],
"first_substantive_response_at": string | null,
"human_review_required": boolean,
"id": string,
"intake_completed_at": string | null,
"intake_mode": Database["public"]['Enums']["intake_mode"] | null,
"intake_status": Database["public"]['Enums']["intake_status"],
"is_demo": boolean,
"machine_number": string | null,
"manual_minutes_baseline": number | null,
"manufacturer": string | null,
"model_type": string | null,
"phone_number": string,
"postal_code": string,
"priority": Database["public"]['Enums']["request_priority"] | null,
"raw_payload": NonNullable<Json>,
"rejection_reason": string | null,
"request_number": string,
"requested_visit_date": string,
"response_due_at": string | null,
"safety_risk": Database["public"]['Enums']["safety_risk"],
"service_due_at": string | null,
"service_kind": Database["public"]['Enums']["service_kind"],
"site_label": string | null,
"sla_contract_number": string | null,
"sla_verified": boolean,
"source": string,
"source_event_key": string,
"street_house_number": string,
"technician_id": string | null,
"updated_at": string,
"version": number,
"work_status": Database["public"]['Enums']["work_status"]
            }
                          SetofOptions: {
        from: "*"
        to: "requests"
        isOneToOne: true
        isSetofReturn: false
      } },
"complete_incoming_message":
{ Args: { "message_id": string,"warnings"?: Json }; Returns: Json
                           },
"complete_intake":
{ Args: { "expected_version": number,"note"?: string,"priority"?: Database["public"]['Enums']["request_priority"],"request_id": string }; Returns: {
              "business_email": string,
"cancellation_reason": string | null,
"cancelled_at": string | null,
"city": string,
"company_name": string,
"completed_at": string | null,
"completion_summary": string | null,
"contact_name": string,
"created_at": string,
"customer_number": string | null,
"customer_urgency": Database["public"]['Enums']["customer_urgency"],
"description": string,
"dispatcher_id": string | null,
"emergency_sla_claimed": boolean | null,
"equipment_kind": Database["public"]['Enums']["equipment_kind"],
"first_substantive_response_at": string | null,
"human_review_required": boolean,
"id": string,
"intake_completed_at": string | null,
"intake_mode": Database["public"]['Enums']["intake_mode"] | null,
"intake_status": Database["public"]['Enums']["intake_status"],
"is_demo": boolean,
"machine_number": string | null,
"manual_minutes_baseline": number | null,
"manufacturer": string | null,
"model_type": string | null,
"phone_number": string,
"postal_code": string,
"priority": Database["public"]['Enums']["request_priority"] | null,
"raw_payload": NonNullable<Json>,
"rejection_reason": string | null,
"request_number": string,
"requested_visit_date": string,
"response_due_at": string | null,
"safety_risk": Database["public"]['Enums']["safety_risk"],
"service_due_at": string | null,
"service_kind": Database["public"]['Enums']["service_kind"],
"site_label": string | null,
"sla_contract_number": string | null,
"sla_verified": boolean,
"source": string,
"source_event_key": string,
"street_house_number": string,
"technician_id": string | null,
"updated_at": string,
"version": number,
"work_status": Database["public"]['Enums']["work_status"]
            }
                          SetofOptions: {
        from: "*"
        to: "requests"
        isOneToOne: true
        isSetofReturn: false
      } },
"complete_visit":
{ Args: { "actual_work_minutes": number,"expected_version": number,"follow_up_reason"?: string,"summary"?: string,"visit_id": string }; Returns: {
              "actual_end": string | null,
"actual_start": string | null,
"actual_work_minutes": number | null,
"cancellation_reason": string | null,
"created_at": string,
"created_by": string,
"id": string,
"request_id": string,
"scheduled_end": string,
"scheduled_start": string,
"status": Database["public"]['Enums']["visit_status"],
"summary": string | null,
"technician_id": string,
"updated_at": string,
"waiting_reason": string | null
            }
                          SetofOptions: {
        from: "*"
        to: "visits"
        isOneToOne: true
        isSetofReturn: false
      } },
"confirm_message_sent":
{ Args: { "gmail_message_id"?: string,"gmail_thread_id"?: string,"mailbox_key"?: string,"message_id": string,"mime_message_id"?: string,"sent_at"?: string }; Returns: {
              "approved_at": string | null,
"approved_by": string | null,
"author_id": string | null,
"body_text": string,
"created_at": string,
"direction": Database["public"]['Enums']["message_direction"],
"error_text": string | null,
"from_address": string | null,
"gmail_message_id": string | null,
"gmail_thread_id": string | null,
"handled_at": string | null,
"id": string,
"in_reply_to": string | null,
"inbox_dispatcher_id": string | null,
"invoice_id": string | null,
"kind": Database["public"]['Enums']["message_kind"],
"mailbox_key": string | null,
"mime_message_id": string | null,
"received_at": string | null,
"references_header": (string)[] | null,
"request_id": string | null,
"sent_at": string | null,
"status": Database["public"]['Enums']["message_status"],
"subject": string,
"to_address": string | null,
"updated_at": string
            }
                          SetofOptions: {
        from: "*"
        to: "messages"
        isOneToOne: true
        isSetofReturn: false
      } },
"confirm_message_sent_base":
{ Args: { "gmail_message_id"?: string,"gmail_thread_id"?: string,"mailbox_key"?: string,"message_id": string,"mime_message_id"?: string,"sent_at"?: string }; Returns: {
              "approved_at": string | null,
"approved_by": string | null,
"author_id": string | null,
"body_text": string,
"created_at": string,
"direction": Database["public"]['Enums']["message_direction"],
"error_text": string | null,
"from_address": string | null,
"gmail_message_id": string | null,
"gmail_thread_id": string | null,
"handled_at": string | null,
"id": string,
"in_reply_to": string | null,
"inbox_dispatcher_id": string | null,
"invoice_id": string | null,
"kind": Database["public"]['Enums']["message_kind"],
"mailbox_key": string | null,
"mime_message_id": string | null,
"received_at": string | null,
"references_header": (string)[] | null,
"request_id": string | null,
"sent_at": string | null,
"status": Database["public"]['Enums']["message_status"],
"subject": string,
"to_address": string | null,
"updated_at": string
            }
                          SetofOptions: {
        from: "*"
        to: "messages"
        isOneToOne: true
        isSetofReturn: false
      } },
"correct_analysis":
{ Args: { "automation_run_id"?: string,"expected_version": number,"priority"?: Database["public"]['Enums']["request_priority"],"reason": string,"request_id": string,"service_kind"?: Database["public"]['Enums']["service_kind"] }; Returns: {
              "business_email": string,
"cancellation_reason": string | null,
"cancelled_at": string | null,
"city": string,
"company_name": string,
"completed_at": string | null,
"completion_summary": string | null,
"contact_name": string,
"created_at": string,
"customer_number": string | null,
"customer_urgency": Database["public"]['Enums']["customer_urgency"],
"description": string,
"dispatcher_id": string | null,
"emergency_sla_claimed": boolean | null,
"equipment_kind": Database["public"]['Enums']["equipment_kind"],
"first_substantive_response_at": string | null,
"human_review_required": boolean,
"id": string,
"intake_completed_at": string | null,
"intake_mode": Database["public"]['Enums']["intake_mode"] | null,
"intake_status": Database["public"]['Enums']["intake_status"],
"is_demo": boolean,
"machine_number": string | null,
"manual_minutes_baseline": number | null,
"manufacturer": string | null,
"model_type": string | null,
"phone_number": string,
"postal_code": string,
"priority": Database["public"]['Enums']["request_priority"] | null,
"raw_payload": NonNullable<Json>,
"rejection_reason": string | null,
"request_number": string,
"requested_visit_date": string,
"response_due_at": string | null,
"safety_risk": Database["public"]['Enums']["safety_risk"],
"service_due_at": string | null,
"service_kind": Database["public"]['Enums']["service_kind"],
"site_label": string | null,
"sla_contract_number": string | null,
"sla_verified": boolean,
"source": string,
"source_event_key": string,
"street_house_number": string,
"technician_id": string | null,
"updated_at": string,
"version": number,
"work_status": Database["public"]['Enums']["work_status"]
            }
                          SetofOptions: {
        from: "*"
        to: "requests"
        isOneToOne: true
        isSetofReturn: false
      } },
"create_invoice":
{ Args: { "expected_version": number,"request_id": string }; Returns: {
              "created_at": string,
"created_by": string,
"currency": string,
"customer_snapshot": NonNullable<Json>,
"id": string,
"invoice_number": string | null,
"issue_date": string | null,
"issued_at": string | null,
"issued_by": string | null,
"notes": string | null,
"paid_at": string | null,
"payment_due_date": string | null,
"request_id": string,
"seller_snapshot": NonNullable<Json>,
"sent_at": string | null,
"status": Database["public"]['Enums']["invoice_status"],
"subtotal": number,
"tax_total": number,
"total": number,
"updated_at": string
            }
                          SetofOptions: {
        from: "*"
        to: "invoices"
        isOneToOne: true
        isSetofReturn: false
      } },
"create_message_draft":
{ Args: { "body_text": string,"expected_version": number,"invoice_id"?: string,"kind": Database["public"]['Enums']["message_kind"],"request_id": string,"subject": string,"to_address": string }; Returns: {
              "approved_at": string | null,
"approved_by": string | null,
"author_id": string | null,
"body_text": string,
"created_at": string,
"direction": Database["public"]['Enums']["message_direction"],
"error_text": string | null,
"from_address": string | null,
"gmail_message_id": string | null,
"gmail_thread_id": string | null,
"handled_at": string | null,
"id": string,
"in_reply_to": string | null,
"inbox_dispatcher_id": string | null,
"invoice_id": string | null,
"kind": Database["public"]['Enums']["message_kind"],
"mailbox_key": string | null,
"mime_message_id": string | null,
"received_at": string | null,
"references_header": (string)[] | null,
"request_id": string | null,
"sent_at": string | null,
"status": Database["public"]['Enums']["message_status"],
"subject": string,
"to_address": string | null,
"updated_at": string
            }
                          SetofOptions: {
        from: "*"
        to: "messages"
        isOneToOne: true
        isSetofReturn: false
      } },
"demo_seed_apply":
{ Args: { "payload": Json }; Returns: Json
                           },
"demo_seed_purge":
{ Args: Record<PropertyKey, never>; Returns: Json
                           },
"find_submission":
{ Args: { "submission_id": string }; Returns: Json
                           },
"finish_automation_run":
{ Args: { "confidence"?: number,"decision"?: Database["public"]['Enums']["automation_decision"],"error_code"?: string,"error_text"?: string,"result"?: Json,"run_id": string,"status": Database["public"]['Enums']["automation_status"],"workflow_execution_id"?: string }; Returns: {
              "confidence": number | null,
"corrected_at": string | null,
"corrected_by": string | null,
"correction_reason": string | null,
"created_at": string,
"decision": Database["public"]['Enums']["automation_decision"] | null,
"error_code": string | null,
"error_text": string | null,
"finished_at": string | null,
"id": string,
"input_version": number | null,
"message_id": string | null,
"operation_key": string,
"request_id": string | null,
"result": Json | null,
"started_at": string,
"status": Database["public"]['Enums']["automation_status"],
"step": Database["public"]['Enums']["automation_step"],
"updated_at": string,
"workflow_execution_id": string | null
            }
                          SetofOptions: {
        from: "*"
        to: "automation_runs"
        isOneToOne: true
        isSetofReturn: false
      } },
"get_analysis_context":
{ Args: { "message_id"?: string,"request_id": string }; Returns: Json
                           },
"ingest_submission":
{ Args: { "payload": Json }; Returns: {
              "business_email": string,
"cancellation_reason": string | null,
"cancelled_at": string | null,
"city": string,
"company_name": string,
"completed_at": string | null,
"completion_summary": string | null,
"contact_name": string,
"created_at": string,
"customer_number": string | null,
"customer_urgency": Database["public"]['Enums']["customer_urgency"],
"description": string,
"dispatcher_id": string | null,
"emergency_sla_claimed": boolean | null,
"equipment_kind": Database["public"]['Enums']["equipment_kind"],
"first_substantive_response_at": string | null,
"human_review_required": boolean,
"id": string,
"intake_completed_at": string | null,
"intake_mode": Database["public"]['Enums']["intake_mode"] | null,
"intake_status": Database["public"]['Enums']["intake_status"],
"is_demo": boolean,
"machine_number": string | null,
"manual_minutes_baseline": number | null,
"manufacturer": string | null,
"model_type": string | null,
"phone_number": string,
"postal_code": string,
"priority": Database["public"]['Enums']["request_priority"] | null,
"raw_payload": NonNullable<Json>,
"rejection_reason": string | null,
"request_number": string,
"requested_visit_date": string,
"response_due_at": string | null,
"safety_risk": Database["public"]['Enums']["safety_risk"],
"service_due_at": string | null,
"service_kind": Database["public"]['Enums']["service_kind"],
"site_label": string | null,
"sla_contract_number": string | null,
"sla_verified": boolean,
"source": string,
"source_event_key": string,
"street_house_number": string,
"technician_id": string | null,
"updated_at": string,
"version": number,
"work_status": Database["public"]['Enums']["work_status"]
            }
                          SetofOptions: {
        from: "*"
        to: "requests"
        isOneToOne: true
        isSetofReturn: false
      } },
"issue_invoice":
{ Args: { "expected_version": number,"invoice_id": string }; Returns: {
              "created_at": string,
"created_by": string,
"currency": string,
"customer_snapshot": NonNullable<Json>,
"id": string,
"invoice_number": string | null,
"issue_date": string | null,
"issued_at": string | null,
"issued_by": string | null,
"notes": string | null,
"paid_at": string | null,
"payment_due_date": string | null,
"request_id": string,
"seller_snapshot": NonNullable<Json>,
"sent_at": string | null,
"status": Database["public"]['Enums']["invoice_status"],
"subtotal": number,
"tax_total": number,
"total": number,
"updated_at": string
            }
                          SetofOptions: {
        from: "*"
        to: "invoices"
        isOneToOne: true
        isSetofReturn: false
      } },
"link_message":
{ Args: { "expected_version": number,"message_id": string,"request_id": string }; Returns: {
              "approved_at": string | null,
"approved_by": string | null,
"author_id": string | null,
"body_text": string,
"created_at": string,
"direction": Database["public"]['Enums']["message_direction"],
"error_text": string | null,
"from_address": string | null,
"gmail_message_id": string | null,
"gmail_thread_id": string | null,
"handled_at": string | null,
"id": string,
"in_reply_to": string | null,
"inbox_dispatcher_id": string | null,
"invoice_id": string | null,
"kind": Database["public"]['Enums']["message_kind"],
"mailbox_key": string | null,
"mime_message_id": string | null,
"received_at": string | null,
"references_header": (string)[] | null,
"request_id": string | null,
"sent_at": string | null,
"status": Database["public"]['Enums']["message_status"],
"subject": string,
"to_address": string | null,
"updated_at": string
            }
                          SetofOptions: {
        from: "*"
        to: "messages"
        isOneToOne: true
        isSetofReturn: false
      } },
"list_incomplete_incoming":
{ Args: { "batch_limit"?: number }; Returns: Json[]
                           },
"list_orphaned_integration_files":
{ Args: Record<PropertyKey, never>; Returns: Json[]
                           },
"list_pending_analyses":
{ Args: { "batch_limit"?: number }; Returns: Json[]
                           },
"mark_awaiting_customer":
{ Args: { "expected_version": number,"note"?: string,"request_id": string }; Returns: {
              "business_email": string,
"cancellation_reason": string | null,
"cancelled_at": string | null,
"city": string,
"company_name": string,
"completed_at": string | null,
"completion_summary": string | null,
"contact_name": string,
"created_at": string,
"customer_number": string | null,
"customer_urgency": Database["public"]['Enums']["customer_urgency"],
"description": string,
"dispatcher_id": string | null,
"emergency_sla_claimed": boolean | null,
"equipment_kind": Database["public"]['Enums']["equipment_kind"],
"first_substantive_response_at": string | null,
"human_review_required": boolean,
"id": string,
"intake_completed_at": string | null,
"intake_mode": Database["public"]['Enums']["intake_mode"] | null,
"intake_status": Database["public"]['Enums']["intake_status"],
"is_demo": boolean,
"machine_number": string | null,
"manual_minutes_baseline": number | null,
"manufacturer": string | null,
"model_type": string | null,
"phone_number": string,
"postal_code": string,
"priority": Database["public"]['Enums']["request_priority"] | null,
"raw_payload": NonNullable<Json>,
"rejection_reason": string | null,
"request_number": string,
"requested_visit_date": string,
"response_due_at": string | null,
"safety_risk": Database["public"]['Enums']["safety_risk"],
"service_due_at": string | null,
"service_kind": Database["public"]['Enums']["service_kind"],
"site_label": string | null,
"sla_contract_number": string | null,
"sla_verified": boolean,
"source": string,
"source_event_key": string,
"street_house_number": string,
"technician_id": string | null,
"updated_at": string,
"version": number,
"work_status": Database["public"]['Enums']["work_status"]
            }
                          SetofOptions: {
        from: "*"
        to: "requests"
        isOneToOne: true
        isSetofReturn: false
      } },
"mark_message_failed":
{ Args: { "error_text": string,"message_id": string,"permanent"?: boolean }; Returns: {
              "approved_at": string | null,
"approved_by": string | null,
"author_id": string | null,
"body_text": string,
"created_at": string,
"direction": Database["public"]['Enums']["message_direction"],
"error_text": string | null,
"from_address": string | null,
"gmail_message_id": string | null,
"gmail_thread_id": string | null,
"handled_at": string | null,
"id": string,
"in_reply_to": string | null,
"inbox_dispatcher_id": string | null,
"invoice_id": string | null,
"kind": Database["public"]['Enums']["message_kind"],
"mailbox_key": string | null,
"mime_message_id": string | null,
"received_at": string | null,
"references_header": (string)[] | null,
"request_id": string | null,
"sent_at": string | null,
"status": Database["public"]['Enums']["message_status"],
"subject": string,
"to_address": string | null,
"updated_at": string
            }
                          SetofOptions: {
        from: "*"
        to: "messages"
        isOneToOne: true
        isSetofReturn: false
      } },
"mark_needs_review":
{ Args: { "expected_version": number,"note"?: string,"request_id": string }; Returns: {
              "business_email": string,
"cancellation_reason": string | null,
"cancelled_at": string | null,
"city": string,
"company_name": string,
"completed_at": string | null,
"completion_summary": string | null,
"contact_name": string,
"created_at": string,
"customer_number": string | null,
"customer_urgency": Database["public"]['Enums']["customer_urgency"],
"description": string,
"dispatcher_id": string | null,
"emergency_sla_claimed": boolean | null,
"equipment_kind": Database["public"]['Enums']["equipment_kind"],
"first_substantive_response_at": string | null,
"human_review_required": boolean,
"id": string,
"intake_completed_at": string | null,
"intake_mode": Database["public"]['Enums']["intake_mode"] | null,
"intake_status": Database["public"]['Enums']["intake_status"],
"is_demo": boolean,
"machine_number": string | null,
"manual_minutes_baseline": number | null,
"manufacturer": string | null,
"model_type": string | null,
"phone_number": string,
"postal_code": string,
"priority": Database["public"]['Enums']["request_priority"] | null,
"raw_payload": NonNullable<Json>,
"rejection_reason": string | null,
"request_number": string,
"requested_visit_date": string,
"response_due_at": string | null,
"safety_risk": Database["public"]['Enums']["safety_risk"],
"service_due_at": string | null,
"service_kind": Database["public"]['Enums']["service_kind"],
"site_label": string | null,
"sla_contract_number": string | null,
"sla_verified": boolean,
"source": string,
"source_event_key": string,
"street_house_number": string,
"technician_id": string | null,
"updated_at": string,
"version": number,
"work_status": Database["public"]['Enums']["work_status"]
            }
                          SetofOptions: {
        from: "*"
        to: "requests"
        isOneToOne: true
        isSetofReturn: false
      } },
"queue_message":
{ Args: { "expected_version": number,"message_id": string }; Returns: {
              "approved_at": string | null,
"approved_by": string | null,
"author_id": string | null,
"body_text": string,
"created_at": string,
"direction": Database["public"]['Enums']["message_direction"],
"error_text": string | null,
"from_address": string | null,
"gmail_message_id": string | null,
"gmail_thread_id": string | null,
"handled_at": string | null,
"id": string,
"in_reply_to": string | null,
"inbox_dispatcher_id": string | null,
"invoice_id": string | null,
"kind": Database["public"]['Enums']["message_kind"],
"mailbox_key": string | null,
"mime_message_id": string | null,
"received_at": string | null,
"references_header": (string)[] | null,
"request_id": string | null,
"sent_at": string | null,
"status": Database["public"]['Enums']["message_status"],
"subject": string,
"to_address": string | null,
"updated_at": string
            }
                          SetofOptions: {
        from: "*"
        to: "messages"
        isOneToOne: true
        isSetofReturn: false
      } },
"record_incoming_message":
{ Args: { "payload": Json }; Returns: Json
                           },
"record_payment":
{ Args: { "expected_version": number,"invoice_id": string,"paid_at"?: string }; Returns: {
              "created_at": string,
"created_by": string,
"currency": string,
"customer_snapshot": NonNullable<Json>,
"id": string,
"invoice_number": string | null,
"issue_date": string | null,
"issued_at": string | null,
"issued_by": string | null,
"notes": string | null,
"paid_at": string | null,
"payment_due_date": string | null,
"request_id": string,
"seller_snapshot": NonNullable<Json>,
"sent_at": string | null,
"status": Database["public"]['Enums']["invoice_status"],
"subtotal": number,
"tax_total": number,
"total": number,
"updated_at": string
            }
                          SetofOptions: {
        from: "*"
        to: "invoices"
        isOneToOne: true
        isSetofReturn: false
      } },
"register_incoming_attachment":
{ Args: { "file_name": string,"message_id": string,"mime_type": string,"size_bytes": number,"storage_path": string }; Returns: {
              "bucket": string,
"created_at": string,
"file_name": string,
"id": string,
"invoice_id": string | null,
"message_id": string | null,
"mime_type": string,
"request_id": string | null,
"size_bytes": number,
"storage_path": string,
"uploaded_by": string | null,
"visibility": Database["public"]['Enums']["visibility_level"],
"visit_id": string | null
            }
                          SetofOptions: {
        from: "*"
        to: "attachments"
        isOneToOne: true
        isSetofReturn: false
      } },
"reject_request":
{ Args: { "expected_version": number,"reason": string,"request_id": string }; Returns: {
              "business_email": string,
"cancellation_reason": string | null,
"cancelled_at": string | null,
"city": string,
"company_name": string,
"completed_at": string | null,
"completion_summary": string | null,
"contact_name": string,
"created_at": string,
"customer_number": string | null,
"customer_urgency": Database["public"]['Enums']["customer_urgency"],
"description": string,
"dispatcher_id": string | null,
"emergency_sla_claimed": boolean | null,
"equipment_kind": Database["public"]['Enums']["equipment_kind"],
"first_substantive_response_at": string | null,
"human_review_required": boolean,
"id": string,
"intake_completed_at": string | null,
"intake_mode": Database["public"]['Enums']["intake_mode"] | null,
"intake_status": Database["public"]['Enums']["intake_status"],
"is_demo": boolean,
"machine_number": string | null,
"manual_minutes_baseline": number | null,
"manufacturer": string | null,
"model_type": string | null,
"phone_number": string,
"postal_code": string,
"priority": Database["public"]['Enums']["request_priority"] | null,
"raw_payload": NonNullable<Json>,
"rejection_reason": string | null,
"request_number": string,
"requested_visit_date": string,
"response_due_at": string | null,
"safety_risk": Database["public"]['Enums']["safety_risk"],
"service_due_at": string | null,
"service_kind": Database["public"]['Enums']["service_kind"],
"site_label": string | null,
"sla_contract_number": string | null,
"sla_verified": boolean,
"source": string,
"source_event_key": string,
"street_house_number": string,
"technician_id": string | null,
"updated_at": string,
"version": number,
"work_status": Database["public"]['Enums']["work_status"]
            }
                          SetofOptions: {
        from: "*"
        to: "requests"
        isOneToOne: true
        isSetofReturn: false
      } },
"reopen_intake":
{ Args: { "expected_version": number,"reason": string,"request_id": string,"target_status": Database["public"]['Enums']["intake_status"] }; Returns: {
              "business_email": string,
"cancellation_reason": string | null,
"cancelled_at": string | null,
"city": string,
"company_name": string,
"completed_at": string | null,
"completion_summary": string | null,
"contact_name": string,
"created_at": string,
"customer_number": string | null,
"customer_urgency": Database["public"]['Enums']["customer_urgency"],
"description": string,
"dispatcher_id": string | null,
"emergency_sla_claimed": boolean | null,
"equipment_kind": Database["public"]['Enums']["equipment_kind"],
"first_substantive_response_at": string | null,
"human_review_required": boolean,
"id": string,
"intake_completed_at": string | null,
"intake_mode": Database["public"]['Enums']["intake_mode"] | null,
"intake_status": Database["public"]['Enums']["intake_status"],
"is_demo": boolean,
"machine_number": string | null,
"manual_minutes_baseline": number | null,
"manufacturer": string | null,
"model_type": string | null,
"phone_number": string,
"postal_code": string,
"priority": Database["public"]['Enums']["request_priority"] | null,
"raw_payload": NonNullable<Json>,
"rejection_reason": string | null,
"request_number": string,
"requested_visit_date": string,
"response_due_at": string | null,
"safety_risk": Database["public"]['Enums']["safety_risk"],
"service_due_at": string | null,
"service_kind": Database["public"]['Enums']["service_kind"],
"site_label": string | null,
"sla_contract_number": string | null,
"sla_verified": boolean,
"source": string,
"source_event_key": string,
"street_house_number": string,
"technician_id": string | null,
"updated_at": string,
"version": number,
"work_status": Database["public"]['Enums']["work_status"]
            }
                          SetofOptions: {
        from: "*"
        to: "requests"
        isOneToOne: true
        isSetofReturn: false
      } },
"reschedule_visit":
{ Args: { "expected_version": number,"reason": string,"scheduled_end": string,"scheduled_start": string,"technician_id"?: string,"visit_id": string }; Returns: {
              "actual_end": string | null,
"actual_start": string | null,
"actual_work_minutes": number | null,
"cancellation_reason": string | null,
"created_at": string,
"created_by": string,
"id": string,
"request_id": string,
"scheduled_end": string,
"scheduled_start": string,
"status": Database["public"]['Enums']["visit_status"],
"summary": string | null,
"technician_id": string,
"updated_at": string,
"waiting_reason": string | null
            }
                          SetofOptions: {
        from: "*"
        to: "visits"
        isOneToOne: true
        isSetofReturn: false
      } },
"resume_analysis":
{ Args: { "expected_version": number,"note"?: string,"request_id": string }; Returns: {
              "business_email": string,
"cancellation_reason": string | null,
"cancelled_at": string | null,
"city": string,
"company_name": string,
"completed_at": string | null,
"completion_summary": string | null,
"contact_name": string,
"created_at": string,
"customer_number": string | null,
"customer_urgency": Database["public"]['Enums']["customer_urgency"],
"description": string,
"dispatcher_id": string | null,
"emergency_sla_claimed": boolean | null,
"equipment_kind": Database["public"]['Enums']["equipment_kind"],
"first_substantive_response_at": string | null,
"human_review_required": boolean,
"id": string,
"intake_completed_at": string | null,
"intake_mode": Database["public"]['Enums']["intake_mode"] | null,
"intake_status": Database["public"]['Enums']["intake_status"],
"is_demo": boolean,
"machine_number": string | null,
"manual_minutes_baseline": number | null,
"manufacturer": string | null,
"model_type": string | null,
"phone_number": string,
"postal_code": string,
"priority": Database["public"]['Enums']["request_priority"] | null,
"raw_payload": NonNullable<Json>,
"rejection_reason": string | null,
"request_number": string,
"requested_visit_date": string,
"response_due_at": string | null,
"safety_risk": Database["public"]['Enums']["safety_risk"],
"service_due_at": string | null,
"service_kind": Database["public"]['Enums']["service_kind"],
"site_label": string | null,
"sla_contract_number": string | null,
"sla_verified": boolean,
"source": string,
"source_event_key": string,
"street_house_number": string,
"technician_id": string | null,
"updated_at": string,
"version": number,
"work_status": Database["public"]['Enums']["work_status"]
            }
                          SetofOptions: {
        from: "*"
        to: "requests"
        isOneToOne: true
        isSetofReturn: false
      } },
"resume_visit":
{ Args: { "expected_version": number,"visit_id": string }; Returns: {
              "actual_end": string | null,
"actual_start": string | null,
"actual_work_minutes": number | null,
"cancellation_reason": string | null,
"created_at": string,
"created_by": string,
"id": string,
"request_id": string,
"scheduled_end": string,
"scheduled_start": string,
"status": Database["public"]['Enums']["visit_status"],
"summary": string | null,
"technician_id": string,
"updated_at": string,
"waiting_reason": string | null
            }
                          SetofOptions: {
        from: "*"
        to: "visits"
        isOneToOne: true
        isSetofReturn: false
      } },
"schedule_visit":
{ Args: { "expected_version": number,"request_id": string,"scheduled_end": string,"scheduled_start": string,"technician_id": string }; Returns: {
              "actual_end": string | null,
"actual_start": string | null,
"actual_work_minutes": number | null,
"cancellation_reason": string | null,
"created_at": string,
"created_by": string,
"id": string,
"request_id": string,
"scheduled_end": string,
"scheduled_start": string,
"status": Database["public"]['Enums']["visit_status"],
"summary": string | null,
"technician_id": string,
"updated_at": string,
"waiting_reason": string | null
            }
                          SetofOptions: {
        from: "*"
        to: "visits"
        isOneToOne: true
        isSetofReturn: false
      } },
"set_work_entry_status":
{ Args: { "expected_version": number,"new_status": Database["public"]['Enums']["work_item_status"],"work_entry_id": string }; Returns: {
              "author_id": string,
"billable": boolean,
"created_at": string,
"description": string,
"id": string,
"item_status": Database["public"]['Enums']["work_item_status"],
"kind": Database["public"]['Enums']["work_entry_kind"],
"ordered_at": string | null,
"performed_at": string | null,
"quantity": number,
"request_id": string,
"service_rate_id": string | null,
"tax_rate": number,
"unit": Database["public"]['Enums']["work_unit"],
"unit_price": number,
"updated_at": string,
"visit_id": string | null
            }
                          SetofOptions: {
        from: "*"
        to: "work_entries"
        isOneToOne: true
        isSetofReturn: false
      } },
"start_automation_run":
{ Args: { "input_version"?: number,"message_id"?: string,"operation_key": string,"request_id"?: string,"step": Database["public"]['Enums']["automation_step"],"workflow_execution_id"?: string }; Returns: Json
                           },
"start_visit":
{ Args: { "expected_version": number,"visit_id": string }; Returns: {
              "actual_end": string | null,
"actual_start": string | null,
"actual_work_minutes": number | null,
"cancellation_reason": string | null,
"created_at": string,
"created_by": string,
"id": string,
"request_id": string,
"scheduled_end": string,
"scheduled_start": string,
"status": Database["public"]['Enums']["visit_status"],
"summary": string | null,
"technician_id": string,
"updated_at": string,
"waiting_reason": string | null
            }
                          SetofOptions: {
        from: "*"
        to: "visits"
        isOneToOne: true
        isSetofReturn: false
      } },
"technician_busy_intervals":
{ Args: { "range_end": string,"range_start": string }; Returns: {
              "busy_kind": string,"ends_at": string,"starts_at": string,"technician_id": string
            }[]
                           },
"technician_experience":
{ Args: { "request_id": string }; Returns: {
              "customer_visits": number,"equipment_visits": number,"manufacturer_visits": number,"technician_id": string
            }[]
                           },
"update_message_draft":
{ Args: { "body_text"?: string,"expected_version": number,"message_id": string,"subject"?: string,"to_address"?: string }; Returns: {
              "approved_at": string | null,
"approved_by": string | null,
"author_id": string | null,
"body_text": string,
"created_at": string,
"direction": Database["public"]['Enums']["message_direction"],
"error_text": string | null,
"from_address": string | null,
"gmail_message_id": string | null,
"gmail_thread_id": string | null,
"handled_at": string | null,
"id": string,
"in_reply_to": string | null,
"inbox_dispatcher_id": string | null,
"invoice_id": string | null,
"kind": Database["public"]['Enums']["message_kind"],
"mailbox_key": string | null,
"mime_message_id": string | null,
"received_at": string | null,
"references_header": (string)[] | null,
"request_id": string | null,
"sent_at": string | null,
"status": Database["public"]['Enums']["message_status"],
"subject": string,
"to_address": string | null,
"updated_at": string
            }
                          SetofOptions: {
        from: "*"
        to: "messages"
        isOneToOne: true
        isSetofReturn: false
      } },
"update_work_entry":
{ Args: { "billable"?: boolean,"description"?: string,"expected_version": number,"quantity"?: number,"unit_price"?: number,"work_entry_id": string }; Returns: {
              "author_id": string,
"billable": boolean,
"created_at": string,
"description": string,
"id": string,
"item_status": Database["public"]['Enums']["work_item_status"],
"kind": Database["public"]['Enums']["work_entry_kind"],
"ordered_at": string | null,
"performed_at": string | null,
"quantity": number,
"request_id": string,
"service_rate_id": string | null,
"tax_rate": number,
"unit": Database["public"]['Enums']["work_unit"],
"unit_price": number,
"updated_at": string,
"visit_id": string | null
            }
                          SetofOptions: {
        from: "*"
        to: "work_entries"
        isOneToOne: true
        isSetofReturn: false
      } },
"wait_for_parts":
{ Args: { "expected_version": number,"reason": string,"visit_id": string }; Returns: {
              "actual_end": string | null,
"actual_start": string | null,
"actual_work_minutes": number | null,
"cancellation_reason": string | null,
"created_at": string,
"created_by": string,
"id": string,
"request_id": string,
"scheduled_end": string,
"scheduled_start": string,
"status": Database["public"]['Enums']["visit_status"],
"summary": string | null,
"technician_id": string,
"updated_at": string,
"waiting_reason": string | null
            }
                          SetofOptions: {
        from: "*"
        to: "visits"
        isOneToOne: true
        isSetofReturn: false
      } }
          }
          Enums: {
            "actor_type": "user"|"automation"|"system","automation_decision": "ready_for_planning"|"ask_customer"|"human_review"|"matched"|"unmatched"|"sent","automation_status": "running"|"succeeded"|"failed","automation_step": "intake_analysis"|"reply_analysis"|"email_matching"|"email_send","availability_kind": "working_hours"|"absence","billing_model": "fixed"|"hourly","customer_urgency": "planbar"|"zeitnah"|"erheblich"|"production_stop","employee_role": "admin"|"manager"|"dispatcher"|"technician","equipment_kind": "pump"|"compressor"|"ventilation"|"other","intake_mode": "automatic"|"manual"|"human_review","intake_status": "new"|"analyzing"|"needs_review"|"awaiting_customer"|"processed"|"rejected"|"cancelled","invoice_status": "draft"|"issued"|"sent"|"paid","message_direction": "incoming"|"outgoing","message_kind": "receipt"|"clarification"|"customer_reply"|"invoice"|"other","message_status": "draft"|"queued"|"sent"|"received"|"failed","request_priority": "low"|"normal"|"high"|"critical","safety_risk": "none_known"|"known"|"unclear","service_kind": "inspection"|"scheduled_maintenance"|"diagnosis_repair","visibility_level": "operational"|"dispatch"|"management","visit_status": "scheduled"|"in_progress"|"waiting_parts"|"completed"|"cancelled","work_entry_kind": "labor"|"part"|"fixed_service","work_item_status": "planned"|"ordered"|"performed"|"used"|"cancelled","work_status": "not_planned"|"scheduled"|"in_progress"|"waiting_parts"|"completed"|"cancelled","work_unit": "hour"|"piece"|"service"
          }
          CompositeTypes: {
            [_ in never]: never
          }
        }
}

type DatabaseWithoutInternals = Omit<Database, '__InternalSupabase'>

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never
> = DefaultSchemaTableNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
  ? (DefaultSchema["Tables"] & DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
      Row: infer R
    }
    ? R
    : never
  : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never
> = DefaultSchemaTableNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
  ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
      Insert: infer I
    }
    ? I
    : never
  : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never
> = DefaultSchemaTableNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
  ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
      Update: infer U
    }
    ? U
    : never
  : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never
> = DefaultSchemaEnumNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
  ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
  : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never
> = PublicCompositeTypeNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
  ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
  : never

export const Constants = {
  "graphql_public": {
          Enums: {
            
          }
        },"public": {
          Enums: {
            "actor_type": ["user", "automation", "system"],"automation_decision": ["ready_for_planning", "ask_customer", "human_review", "matched", "unmatched", "sent"],"automation_status": ["running", "succeeded", "failed"],"automation_step": ["intake_analysis", "reply_analysis", "email_matching", "email_send"],"availability_kind": ["working_hours", "absence"],"billing_model": ["fixed", "hourly"],"customer_urgency": ["planbar", "zeitnah", "erheblich", "production_stop"],"employee_role": ["admin", "manager", "dispatcher", "technician"],"equipment_kind": ["pump", "compressor", "ventilation", "other"],"intake_mode": ["automatic", "manual", "human_review"],"intake_status": ["new", "analyzing", "needs_review", "awaiting_customer", "processed", "rejected", "cancelled"],"invoice_status": ["draft", "issued", "sent", "paid"],"message_direction": ["incoming", "outgoing"],"message_kind": ["receipt", "clarification", "customer_reply", "invoice", "other"],"message_status": ["draft", "queued", "sent", "received", "failed"],"request_priority": ["low", "normal", "high", "critical"],"safety_risk": ["none_known", "known", "unclear"],"service_kind": ["inspection", "scheduled_maintenance", "diagnosis_repair"],"visibility_level": ["operational", "dispatch", "management"],"visit_status": ["scheduled", "in_progress", "waiting_parts", "completed", "cancelled"],"work_entry_kind": ["labor", "part", "fixed_service"],"work_item_status": ["planned", "ordered", "performed", "used", "cancelled"],"work_status": ["not_planned", "scheduled", "in_progress", "waiting_parts", "completed", "cancelled"],"work_unit": ["hour", "piece", "service"]
          }
        }
} as const
